# Generated by Django 6.0.5 on 2026-05-26 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('rankings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='monthlyranking',
            index=models.Index(fields=['school_class', 'ranking_month'], name='rankings_mo_school__5f53db_idx'),
        ),
    ]
