# Generated by Django 6.0.5 on 2026-05-26 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('payments', '0002_paymentimportbatch_importedtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tuitionpayment',
            index=models.Index(fields=['payment_reference'], name='payments_tu_payment_26af95_idx'),
        ),
    ]
