# Generated by Django 6.0.5 on 2026-05-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='monthly_tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
