# Generated by Django 6.0.5 on 2026-05-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_schoolclass_monthly_tuition_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='monthly_tuition_fee',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='lesson_fee',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=10),
        ),
    ]
