# Generated by Django 6.0.5 on 2026-05-28 05:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_schoolclass_monthly_tuition_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='lesson_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=10),
        ),
    ]
